Created a contact me section at the bottom of the home page
MLH-Fellowship/portfolio-template pull request #28
Opened 2021-02-02 11:11 UTC by anjalisoni3655

- Two fields name and message to be sent is present.
-  Used the formspree to collect the responses from the contact form.

2021-02-02 11:46 UTC, wrussell1999 requested changes
Hey @anjalisoni3655 !

This looks great! I think some folks will find this super useful. I added a few comments but apart from that, I think it looks great!

2021-02-02 11:46 UTC, wrussell1999 commented on _config.yml
> +title: "Will Russel"
My last name has 2 "L"s :D

2021-02-02 11:46 UTC, wrussell1999 commented on index.html
> +      <form action="https://formspree.io/f/xrgodpqo" method="POST">
It would be great if we could have a form_url parameter to `_config.yml` and people can add their own in there.

2021-02-02 11:46 UTC, wrussell1999 commented on index.html
> +    <div class="column">
This could be added as a separate component in Jekyll. You can see the `_includes` folder for inspiration!

2021-02-02 11:46 UTC, wrussell1999 commented on index.html
> +    <div class="column">
Is there a way for us to centre this on the page? :D

2021-02-02 11:56 UTC, anjalisoni3655 commented on _config.yml
> +title: "Will Russel"
Sorry! Will make the changes. 😄

2021-02-02 11:56 UTC, anjalisoni3655 commented on index.html
> +      <form action="https://formspree.io/f/xrgodpqo" method="POST">
Yah, sure! doing that.

2021-02-02 12:59 UTC, anjalisoni3655 commented on _config.yml
> +title: "Will Russel"
changed the spelling error.

2021-02-02 13:00 UTC, anjalisoni3655 commented on index.html
> +      <form action="https://formspree.io/f/xrgodpqo" method="POST">
moved the form_url in _config.yml file and using it from the site variable.

2021-02-02 13:06 UTC, aitikgupta commented on index.html
> +    <div class="column">
This is now refactored into contacts.html :)

2021-02-02 13:06 UTC, aitikgupta commented on index.html
> +    <div class="column">
Yep!

2021-02-02 13:37 UTC, bodhisha commented on index.html
> +    <div class="column">
Done

2021-02-02 14:31 UTC, bodhisha commented
Resolves #28

2021-02-02 15:59 UTC, wrussell1999 commented
Looking great now! I have one last request! 

Could you write a bit in the README explaining how someone can set this up! @bodhisha

2021-02-02 16:04 UTC, bodhisha commented
> Looking great now! I have one last request!
> 
> Could you write a bit in the README explaining how someone can set this up! @bodhisha

Yea sure! Will update

2021-02-03 09:32 UTC, RashikaKarki approved these changes
Everything Looks great :)

2021-02-03 09:32 UTC, RashikaKarki commented on README.md
> +6. All the submissions will be visible on the `submissions` tab. :D
Great job with the readme ✨

2021-02-03 09:45 UTC, merged