Fixes URL and links
MLH-Fellowship/portfolio-template pull request #39
Opened 2021-02-02 12:54 UTC by LucasLobo

I tried running the original repo on Docker and it didn't work because the URLs weren't set up properly.

This PR changes the URL/links such that they are relative. Ideally all future commits follow the same structure when building links.

Here is it running on my page:
[https://lucaslobo.github.io/portfolio-template/](https://lucaslobo.github.io/portfolio-template/)

2021-02-02 12:55 UTC, LucasLobo commented on _config.yml
> +baseurl: "/portfolio-template"
I looked it up and I think that these two were switched originally. From what I understood, _baseurl_ should have the prefix instead of _url_.

2021-02-02 12:55 UTC, LucasLobo commented
I used this thread as a "guide" https://talk.jekyllrb.com/t/relative-url-and-baseurl/2051

2021-02-02 12:56 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
The original `site.url` broke the code. The remaining links are not strictly necessary but they make everything consistent.

2021-02-02 15:35 UTC, LucasLobo commented
I don't have much experience with forks/pull requests. I added support for docker in my fork and it automatically added it to this pull request. That was not intended. Is there a way to add commits without adding them here?

2021-02-02 16:09 UTC, Korusuke commented
Hey Lucas --
Thanks for the PR!

> I don't have much experience with forks/pull requests. I added support for docker in my fork and it automatically added it to this pull request. That was not intended. Is there a way to add commits without adding them here?

Yes, so from what I can see, you have committed to your master branch directly.
Usually when working on something we tend to use branches. 
To resolve your current situation I would suggest the following:
- Go back to [this commit](https://github.com/LucasLobo/portfolio-template/commit/acfdff7954df2373a2d798d50c2f34ea4bdc3cc4) using `git checkout acfdff7954df2373a2d798d50c2f34ea4bdc3cc4`
- Create a new branch there for docker stuff
- then use [git cherry picking](https://stackoverflow.com/questions/9339429/what-does-cherry-picking-a-commit-with-git-mean) to transfer your docker commit from master branch to docker branch

I hope this helps, if there is any issue you can comment here or ping me on discord (Karan Sheth on MLH Fellowship Server)

2021-02-02 16:31 UTC, LucasLobo commented
I think I managed to do it @Korusuke. What remains now should be just what I intended to push to this PR.

2021-02-02 16:59 UTC, Korusuke commented on _config.yml
> +baseurl: "/portfolio-template"
after this change is the website running locally for you?

I tested your PR and opening the `index.html` or the `localhost` server by jekyll throws assets not found error

It does work on github, cause of the way github pages routes work but we should not be aiming just for that

In my opinion both url and baseurl should be just `/` and we should be using relative addressing

2021-02-02 17:02 UTC, Korusuke requested changes
Test in below three ways:
- Does the jekyll server work?
- Does opening the generated `_site/index.html` work while the server is running?
- Does opening the generated `_site/index.html` work while the server is not running?

2021-02-02 17:02 UTC, Korusuke commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
I am not sure what `| relative_url` is supposed to do but adding a `.` dot in front of urls will work just fine imo.
example: `'/assets/css/main.css'` -> './assets/css/main.css'

2021-02-02 17:02 UTC, Korusuke commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
ditto for all relative_url use

2021-02-02 17:10 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
I talked with @wrussell1999 and he said that he used this approach with `{{ site.url }} `on purpose since it was breaking without it on his side. I can't really reproduce it though.

The `| relative_url` adds the `baseurl`, since it's not always simply `/`. I linked the thread that explains it. Anyway, the dot might work.

2021-02-02 17:14 UTC, LucasLobo commented on _config.yml
> +baseurl: "/portfolio-template"
I'm running the Jekyll server and it does work locally for me, as long as I go to the `baseurl ``/portfolio-template`.  It does not work at `/`, but I think that's the expected behavior?

2021-02-02 17:18 UTC, LucasLobo commented
> * Does the jekyll server work?
> * Does opening the generated `_site/index.html` work while the server is running?
> * Does opening the generated `_site/index.html` work while the server is not running?

Well.. I'm running this on Docker, maybe I shouldn't. I start the Jekyll docker server and it works locally, but I can't access the `_site/index.html` files.

2021-02-02 17:19 UTC, Korusuke commented
> Well.. I'm running this on Docker, maybe I shouldn't. I start the Jekyll docker server and it works locally, but I can't access the `_site/index.html` files.

you can use docker volumes to access the `_site` folder

2021-02-02 17:28 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
I just tested this @Korusuke and by using the `.` it only works on the home-page. If you are one a secondary page, the `.` will just add to it. For example, if you are on `/portfolio-template/projects/sprint1` the CSS will link to `/portfolio-template/projects/assets/css/main.css`.

2021-02-02 17:52 UTC, Korusuke commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
Yes you are right, I missed that out. Then I guess you will have to implement the `relative_url` in some way.
In my opinion the website should work in all three cases that I mentioned and there shouldn't be a need to go to `/portfolio-template`. 

Solving this will also fix the netlify deploy issue.

I may be wrong here, let's get a third opinion @wrussell1999

2021-02-02 21:11 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
When I open index.html on the original repo it doesn't work for me either, since it links to 0.0.0.0:4000/assets.

There's probably some way to do this but I don't know enough about Jekyll to make it work to be honest..

2021-02-03 07:14 UTC, Korusuke commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
nope, even then original repo doesn't work in all three ways, and I think we need to fix that

2021-02-03 11:10 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
Do you think that is possible? I'm thinking specifically about clicking on the index.html file. For it to work with the server offline, it needs to link to the file in a path without any server information (e.g., /assets/css instead of 0.0.0.0/assets/css), right? So it has to be a relative path, but then it breaks if it is on a different page (e.g., /projects) since it will just append it at the end (/projects/assets/css).

Unless there's a way to create a relative path starting at the top of the folder structure. I tried that but then locally (clicking on the index.html file) it will just start at the beginning of the C:/ drive instead of at the beginning of the project folder.

Any opinions? Maybe I'm forgetting some way of linking that solves this issue completely.

2021-02-03 12:31 UTC, Korusuke commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
I looked into this and turns out jekyll is designed in a way to be served with a server in place.
So for now lets not think about the scenario of directly opening the `index.html`, although we can do this by add a plugin as mentioned [here](https://github.com/jekyll/jekyll/issues/6360#issuecomment-329275101) but then again this plugin is not whitelisted by github so it won't work on gh pages.

So if you can just solve the conflicts, I will the review the PR again and then lets get this merged.

2021-02-03 15:23 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
I'm not sure where we're at right now. Should everything be changed to `| relative_url` ? And what should happen with `url` and `baseurl`?

2021-02-03 18:19 UTC, jkmartindale commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
I did some research regarding this today to fix #46, and here are my findings:

`url` should be set to the host for when you're deploying, e.g. `https://mlh-fellowship.github.io`. In a development environment, this will automatically be overridden to work locally (see https://jekyllrb.com/docs/variables/#site-variables:~:text=if%20you%20are%20running%20jekyll%20serve,of%20host%2C%20port%2C%20and%20SSL%2Drelated%20options.)

`baseurl` should be set to the root directory you're serving Jekyll pages from. If you're serving it from the root of a domain, it's `/`. If you're using the default GitHub Pages configuration, it's `/repository_name`.

With these set, the `absolute_url` filter will add `url`, `baseurl`, and its input to form a complete absolute URL.

If this is too confusing, an alternative is to use `site.github.url` and append carefully-crafted relative URLs. This will only work on GitHub Pages (or if you install the GitHub Pages environment), so it might not be the ideal approach but it is simpler.

2021-02-03 20:29 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
Yep I think that's it. But why use absolute_url instead of relative_url? At least for the header.html file.

2021-02-03 20:36 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
Also, at this point it's probably easier to just delete this pull request and start fresh. @Korusuke 
I could do it but I need confirmation on what we should actually change it to.

2021-02-03 21:42 UTC, jkmartindale commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
We had to use absolute URLs for the Open Graph metadata because the spec doesn't like relative URLs (https://stackoverflow.com/a/9858694/3427178). If it's alright we have the fixes in our upcoming PR so a new one might not be needed.

2021-02-03 21:53 UTC, LucasLobo commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
Let me know when your PR is up as well so I can take a look. Don't forget to try to open a project page. It might break on the github pages considering it has this link `{{ site.url }}/projects/{{ item.page-name }}`

2021-02-03 21:53 UTC, jkmartindale commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
#67 for the changes to `site.url` and `site.baseurl`

2021-02-03 21:56 UTC, jkmartindale commented on _includes/header.html
> +    <link rel='icon' href="{{ '/assets/img/favicon.ico' | relative_url }}" type='image/x-icon' />
> Don't forget to try to open a project page. It might break on the github pages considering it has this link `{{ site.url }}/projects/{{ item.page-name }}`

Haha woops, forgot to check other links. I'll fix them up and keep pushing.

2021-02-04 15:17 UTC, closed without merging