Add Skill section
MLH-Fellowship/portfolio-template pull request #47
Opened 2021-02-02 17:17 UTC by Abhishek-kumar09

Fixes #4
## Changes
A skill section is added based on catgorization of the skill itself, like Programming skills, framework knowledge and Interpersonal skills in the form of cards.

## How Has This Been Tested?
- This has been tested locally in the systems and in the docker environment with no errors, warnings etc on the console. 
- This has been tested for responsiveness for multiple screens.

## Mentions

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Checklist

- [x] Coding style of this project is followed
- [ ] Change in documentation is required
- [ ] Documentation has been updated accordingly 
- [ ] Unit tests have been added to cover code change

2021-02-02 19:11 UTC, Korusuke requested changes
Hey @Abhishek-kumar09, thanks for submitting the PR!

The code itself looks solid but I am a bit concerned about asset images, is there way to get these from some third party service and not have them in the template?

cause if someone wants to add their own skills they will have to go looking for images and resize that and everything.

2021-02-03 11:40 UTC, Abhishek-kumar09 commented on Gemfile.lock
> +   2.2.2
@Korusuke, This changes are generated automatically when ran on docker, left here by mistake.
Reverted. Done.

2021-02-03 11:41 UTC, Abhishek-kumar09 commented
>  am a bit concerned about asset images, is there way to get these from some third party service and not have them in the template?

yes, I have just added the fontawesome and devIcons to fetch regular and development related icons respectively.

2021-02-03 13:42 UTC, Korusuke requested changes
Woahh!! The skills section looks amazing!

Just had few nitpicks and then this PR is ready to be merged.

I also had one last doubt, currently there 3 in each category but what if I have more how would it look? can u post a screenshot with 6 3 2.

2021-02-03 13:42 UTC, Korusuke commented on _data/skills.yml
> +#frameworks section
nitpick: add a space after `#`

2021-02-03 13:42 UTC, Korusuke commented on _data/skills.yml
> +# #interpersonal section
nitpick: only 1 `# ` should be there for comments

2021-02-03 14:18 UTC, Abhishek-kumar09 commented
Wow, it broke:
![image](https://user-images.githubusercontent.com/48255244/106759390-b719ab00-6658-11eb-8633-29274e8edd0a.png)

Will fix it.

2021-02-03 18:43 UTC, Abhishek-kumar09 commented on _data/skills.yml
> +#frameworks section
Done.

2021-02-03 18:43 UTC, Abhishek-kumar09 commented on _data/skills.yml
> +# #interpersonal section
Done, these are blunders to be honest.

2021-02-03 18:45 UTC, Abhishek-kumar09 commented
> I also had one last doubt, currently there 3 in each category but what if I have more how would it look? can u post a screenshot with 6 3 2.

This is how it will look.
![Screenshot_2021-02-04 Personal Portfolio](https://user-images.githubusercontent.com/48255244/106793835-fa3a4500-667d-11eb-92bf-58120678fca3.png)

2021-02-04 14:06 UTC, Abhishek-kumar09 commented
@Korusuke Please let me know if you have some other suggestions.

2021-02-04 14:23 UTC, Korusuke commented
it looks fine to me, sorry I forgot to merge....merging now!

2021-02-04 14:23 UTC, merged