Footer Added
MLH-Fellowship/portfolio-template pull request #61
Opened 2021-02-03 09:49 UTC by DebugAgrawal

## Changes

Footer added to the portfolio along with links to social media and Jekyll Acknowledgement 
![image](https://user-images.githubusercontent.com/64848982/106728490-8292f880-6632-11eb-9831-dfde837045a5.png)

## How Has This Been Tested?

Tested the code on local machine by creating the suitable environment (Ruby, Bundlers)

Changes made, do not affect any other code as new modules for Footer were added (footer.html, footer.scss)

## Mentions

@DebugAgrawal @iamyevesky and @yvonmanzi are working on this issue

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Checklist

- [x] Coding style of this project is followed
- [ ] Change in documentation is required
- [ ] Documentation has been updated accordingly 
- [ ] Unit tests have been added to cover code change

2021-02-03 10:02 UTC, DebugAgrawal commented
## It's live here : https://debugagrawal.github.io/portfolio-template/ for better view

Yesterday instead of forking the repo we [cloned](https://github.com/DebugAgrawal/mlh-orientation) it and stared creating footer 🙂 
later on today when the footer was [done](https://github.com/DebugAgrawal/mlh-orientation/commit/67e051d948cc3d91062742cdc7a8cc6fd1feeb79) while making a PR there wasn't any option for it, as it was cloned.
So forked the official repo and then made the changes and created a PR

2021-02-03 11:17 UTC, Korusuke requested changes
check inline comments

2021-02-03 11:17 UTC, Korusuke commented on Gemfile.lock
>    jekyll (~> 4.1.1)
do we really need all this extra packages? or is this cause of operating system difference?

2021-02-03 11:17 UTC, Korusuke commented on _includes/footer.html
> +    <a href="https://github.com/{{site.github_username}}" target="_blank"><img src="./assets/img/footer/github.png" alt="github"></a>
Nitpick: If you look closely both the images on page may be of same size (30x30) but since there is white space around the github logo, it makes it look smaller.

In my opinion just switch to using `font-awesome` icons as 1. its already imported and 2. it will be easy to change their colors when #53 and #55 are done.

2021-02-03 11:17 UTC, Korusuke commented on _sass/footer.scss
> +    color: black;
maybe add some margin to left and right sides (not sure abt this)

2021-02-03 11:36 UTC, DebugAgrawal commented on Gemfile.lock
>    jekyll (~> 4.1.1)
my machine has Windows OS so this package was added while 
> Bundle install

2021-02-03 11:40 UTC, DebugAgrawal commented on _includes/footer.html
> +    <a href="https://github.com/{{site.github_username}}" target="_blank"><img src="./assets/img/footer/github.png" alt="github"></a>
working on it 👍

2021-02-03 11:47 UTC, DebugAgrawal commented on _sass/footer.scss
> +    color: black;
Done (added padding instead) looks great now👍

> Before :
![image](https://user-images.githubusercontent.com/64848982/106742813-867b4680-6643-11eb-8129-a78db7a47c7e.png)

> After :
![image](https://user-images.githubusercontent.com/64848982/106742887-a01c8e00-6643-11eb-9d83-b522f7a1e4ab.png)

2021-02-03 11:50 UTC, aitikgupta commented
Since the header has white font behind the blue frame:
![image](https://user-images.githubusercontent.com/43996118/106743132-fab5ea00-6643-11eb-9b39-f312f36e0939.png)

Would it make sense to convert the footer's font to white?
![image](https://user-images.githubusercontent.com/43996118/106743173-099c9c80-6644-11eb-8797-c2f7e9306904.png)

2021-02-03 11:57 UTC, DebugAgrawal commented
> Since the header has white font behind the blue frame:
> ![image](https://user-images.githubusercontent.com/43996118/106743132-fab5ea00-6643-11eb-9b39-f312f36e0939.png)
> 
> Would it make sense to convert the footer's font to white?
> ![image](https://user-images.githubusercontent.com/43996118/106743173-099c9c80-6644-11eb-8797-c2f7e9306904.png)

Yeah makes sense 🙌
Done (working on logos now)
![image](https://user-images.githubusercontent.com/64848982/106743755-cabb1680-6644-11eb-9eef-5fcc945ae051.png)

2021-02-03 12:44 UTC, Korusuke commented
I think #63 is trying to solve the same issue, please co-ordinate with them and find the best way out.

2021-02-03 14:08 UTC, DebugAgrawal commented on _includes/footer.html
> +    <a href="https://github.com/{{site.github_username}}" target="_blank"><img src="./assets/img/footer/github.png" alt="github"></a>
Hey I've made the required changes 
![image](https://user-images.githubusercontent.com/64848982/106758245-4e7dfe80-6657-11eb-9361-38ab09826dfd.png)

2021-02-03 19:21 UTC, Korusuke approved these changes

2021-02-03 19:23 UTC, Korusuke commented
LGTM!
I am not merging this just yet, since #63 is also regarding the same. So I would like to ask @wrussell1999 @RashikaKarki @yashika51 abt what should be done here?

2021-02-03 22:04 UTC, wrussell1999 commented
I think this would be useful to have both, and let people chose. Make them both components in `_includes` and let the people decide.

2021-02-04 00:17 UTC, sachsom95 commented
> I think this would be useful to have both, and let people chose. Make them both components in `_includes` and let the people decide.

I think thats a great suggestion will work on that

2021-02-04 10:47 UTC, DebugAgrawal commented
> I think this would be useful to have both, and let people chose. Make them both components in `_includes` and let the people decide.

Hey so shall we update Readme too regarding the footer choice ?

2021-02-04 11:02 UTC, wrussell1999 commented
Yes please @DebugAgrawal

2021-02-04 11:33 UTC, Korusuke commented
It would be great if you can solve the conflicts so we can get this PR merged too :)

2021-02-04 11:46 UTC, Korusuke commented on _includes/footer.html
> +</footer>
I was under the impression there was supposed to be an option between both the footer's right? am I missing something here?

2021-02-04 11:46 UTC, Korusuke requested changes

2021-02-04 11:46 UTC, Korusuke commented on _sass/all.scss
> +@import 'footer';
ditto

2021-02-04 11:48 UTC, saum7800 commented
@DebugAgrawal , I think you have overwritten the footer.html file. This would take away the option from the user. I think the steps you can follow could be:
1. Add footer_<your choice>.html file.
2. Add footer_<your choice>.scss file.
3. Addfooter_<your choice>.scss to the all.scss file.

This would give the choice.

2021-02-04 11:51 UTC, DebugAgrawal commented on _includes/footer.html
> +</footer>
Oh okay I guess I did a very bad thing here.
Sorry for that I was confused.

2021-02-04 11:53 UTC, DebugAgrawal commented on _sass/all.scss
> +@import 'footer';
I'll work on it 👍

2021-02-04 13:05 UTC, DebugAgrawal commented
Shall I add Images for footer choice in Readme ?
like :
---

You can choose the footer by changing the value of `- footer_file_name :` in `_head/footer.yml` as

1. `footer_flat.html` for

![image](https://user-images.githubusercontent.com/64848982/106896293-62893500-6717-11eb-88d1-d15bb17ec6c6.png)

2. `footer_minimal.html` for

![image](https://user-images.githubusercontent.com/64848982/106896498-a2e8b300-6717-11eb-943e-fc6ad9617aea.png)

2021-02-04 14:23 UTC, Korusuke commented
> ## Shall I add Images for footer choice in Readme ?
> like :
> 
> You can choose the footer by changing the value of `- footer_file_name :` in `_head/footer.yml` as
> 
>     1. `footer_flat.html` for
> 
> 
> ![image](https://user-images.githubusercontent.com/64848982/106896293-62893500-6717-11eb-88d1-d15bb17ec6c6.png)
> 
>     1. `footer_minimal.html` for
> 
> 
> ![image](https://user-images.githubusercontent.com/64848982/106896498-a2e8b300-6717-11eb-943e-fc6ad9617aea.png)

Oh yes, thats a great idea!

2021-02-04 15:17 UTC, saum7800 commented on _includes/footer.html
> +</footer>
@DebugAgrawal , I think that footer.html will need to be reverted to the original. Thanks!

2021-02-04 15:18 UTC, saum7800 commented on _sass/footer.scss
> +.footer{
Since you now have footer_flat.css, this file has become redundant I feel so you can probably remove it. Thanks!

2021-02-04 15:58 UTC, DebugAgrawal commented on _sass/footer.scss
> +.footer{
Done

2021-02-04 15:58 UTC, DebugAgrawal commented on _includes/footer.html
> +</footer>
Done

2021-02-05 06:12 UTC, saum7800 approved these changes
Looks good to me! Thanks for the many changes

2021-02-05 09:37 UTC, Korusuke commented
Thanks a lot for being patient ! <3

2021-02-05 09:38 UTC, merged