Add social media links and footer
MLH-Fellowship/portfolio-template pull request #63
Opened 2021-02-03 12:23 UTC by MyrrhDev

## Changes
All changes made responding to issue #12 :
Added an interactive responsive footer
Added social media links
Included a sass file for the footer
Included a `social-media.yml` file
Added arrow to scroll up from the bottom of the front page

<img width="200" height="200" src="https://cdn.discordapp.com/attachments/806128971607572506/806497255384285225/Screenshot_2021-02-03_at_12.12.03.png"> <img width="220" height="200" src ="https://cdn.discordapp.com/attachments/806128971607572506/806497364881309746/Screenshot_2021-02-03_at_12.12.32.png"><img width="300" height="200" src ="https://cdn.discordapp.com/attachments/806128971607572506/806497460301201448/Screenshot_2021-02-03_at_12.12.54.png">

## How Has This Been Tested?

Ran it through Chrome Lighthouse
Tested responsiveness in different screen sizes, and different internet browsers.

## Mentions

@wrussell1999 @Korusuke if you could please check this out

## Types of changes

- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [X] New feature and improvements (non-breaking change which adds/improves functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [ ] Documentation
- [ ] Test, CI, or build

## Checklist

- [x] Coding style of this project is followed
- [ ] Change in documentation is required
- [ ] Documentation has been updated accordingly 
- [ ] Unit tests have been added to cover code change

2021-02-03 12:44 UTC, Korusuke requested changes
Thanks for the PR! It looks amazing!

I have pointed out some small things, it would be great if you can update the PR accordingly, the nitpicks might feel like torture but its a necessary evil :sweat_smile: 

Also I think #61 is trying to solve the same issue, please co-ordinate with them and find the best way out.

2021-02-03 12:44 UTC, Korusuke commented on Gemfile.lock
> +    wdm (0.1.1)
do we really need all this extra packages? or is this cause of operating system difference?

2021-02-03 12:44 UTC, Korusuke commented on _data/social-media.yml
> +
Nitpick: We usually only keep 1 extra line at the end of file

2021-02-03 12:44 UTC, Korusuke commented on _includes/footer.html
> +        </p>
there are two `</p>` but only one opening, am I missing something here?

2021-02-03 12:44 UTC, Korusuke commented on _includes/header.html
> +    <meta property="og:description" content="My Personal Portfolio">
Nitpick: All though these linting changes are necessary and it's great to see them, I would love to see them in a different PR.

2021-02-03 12:44 UTC, Korusuke commented on _includes/profile.html
> +<div class="profile" >
Nitpick: extra space

2021-02-03 12:44 UTC, Korusuke commented on _includes/social-media-links.html
> +{% endif %}
Make sure to format code, run some html / nunjucks linter

2021-02-03 12:44 UTC, Korusuke commented on index.html
> +<body>
I am not sure if `<body>` tag is necessary or not, since its not there in the original code

2021-02-03 12:52 UTC, MyrrhDev commented on Gemfile.lock
> +    wdm (0.1.1)
I was just about to say we mainly inherited those but I think it's because of OS differences, looks like Windows (?). Not sure if my teammates know more about this @sachsom95 @saum7800

2021-02-03 12:53 UTC, MyrrhDev commented on _includes/footer.html
> +        </p>
No, it's true. About to get solved :)

2021-02-03 12:56 UTC, MyrrhDev commented on index.html
> +<body>
Solved!

2021-02-03 12:58 UTC, MyrrhDev commented on _includes/header.html
> +    <meta property="og:description" content="My Personal Portfolio">
Sure, should we leave it as is for now then?

2021-02-03 13:01 UTC, sachsom95 commented on Gemfile.lock
> +    wdm (0.1.1)
I haven't added any new gems, seems like some of them are windows packages

2021-02-03 13:21 UTC, saum7800 commented on Gemfile.lock
> +    wdm (0.1.1)
yes, those are due to the ruby dependencies because my environment is on Windows.

2021-02-03 13:39 UTC, saum7800 commented on _includes/header.html
> +    <meta property="og:description" content="My Personal Portfolio">
Cool. We have updated it to keep the original linting here

2021-02-03 13:46 UTC, Korusuke commented on _includes/header.html
> +    <meta property="og:description" content="My Personal Portfolio">
Thanks a lot!

2021-02-03 13:46 UTC, Korusuke commented on Gemfile.lock
> +    wdm (0.1.1)
Then let's get rid of them as the github environment is ubuntu

2021-02-04 09:11 UTC, saum7800 commented
@Korusuke , I have added a footer.yml file which takes the filename for whichever footer file a user wishes to use. The required footer file is then included. This will make it easy for #61 to also merge and will give users of the template both choices of footers as @wrussell1999 suggested in #61. Kindly review and let me know what you think. Thanks

2021-02-04 10:10 UTC, sachsom95 commented on _data/footer.yml
> +- footer_file_name: footerA.html
maybe a more understandable name for user who chooses the what footer to use

2021-02-04 10:11 UTC, sachsom95 reviewed
The names for footer seems bit confusing

2021-02-04 10:40 UTC, saum7800 commented on _data/footer.yml
> +- footer_file_name: footerA.html
this is done. thanks.

2021-02-04 11:32 UTC, merged

2021-02-04 11:32 UTC, Korusuke commented
Thanks a lot for making all the changes!