Fix Open Graph + Twitter Card metadata
MLH-Fellowship/portfolio-template pull request #67
Opened 2021-02-03 21:51 UTC by jkmartindale

Fixes #46 

## Changes
- Fixes Open Graph metadata by using absolute URLs (required by spec<sup>[[source]](https://stackoverflow.com/a/9858694/3427178)</sup>)
- Adds a Twitter card
- Fixes `site.url` and `site.baseurl` to match Jekyll convention<sup>[[source]](https://jekyllrb.com/docs/variables/#site-variables:~:text=if%20you%20are%20running%20jekyll%20serve,of%20host%2C%20port%2C%20and%20SSL%2Drelated%20options)</sup> (potentially breaking)
- Added comments to `_config.yml` to document `site.url` and `site.baseurl`

## How Has This Been Tested?
We updated `site.url` and `site.baseurl`, deployed the template to GitHub Pages, and verified results with https://metatags.io/

## Mentions

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] New feature and improvements (non-breaking change which adds/improves functionality)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Code Refactoring (internal change which is not user facing)
- [x] Documentation
- [ ] Test, CI, or build

## Checklist

- [x] Coding style of this project is followed
- [ ] Change in documentation is required
- [x] Documentation has been updated accordingly 
- [ ] Unit tests have been added to cover code change

2021-02-03 22:25 UTC, jkmartindale commented
@LucasLobo unsure if GitHub notifies for mentions coming from edits, so sorry for the double ping if so. I just fixed the project and resume URL generation that would result from the site.url and site.baseurl changes we propose.

2021-02-04 11:38 UTC, Korusuke requested changes

2021-02-04 11:38 UTC, Korusuke commented on _config.yml
> +theme: jekyll-theme-cayman
adding `theme: jekyll-theme-cayman` is causing build issue since its not there in the gemlock. do we need this, what's the purpose of it?

2021-02-04 15:19 UTC, LucasLobo commented
I can't try it out right now, but don't forget to test whether the linking is still working for all pages and sub-pages. That might be a problem due to the change in the` _config.yml` file.

2021-02-05 02:34 UTC, jkmartindale commented on _config.yml
> +theme: jekyll-theme-cayman
I'm honestly not sure where it came from (might be left over from some Jekyll tests/learning), but it's definitely not needed here.

2021-02-05 02:51 UTC, jkmartindale commented
As I understand it, as long as absolute URLs are generated as `{{ '/relative/url' | absolute_url }}`, they should be compatible with whatever changes happen with `site.url` and `site.baseurl` even if the config doesn't exactly match convention. I'm going to check existing code upstream and pending PRs to make sure nobody is doing stuff like `{{ site.url }}/relative/url`

2021-02-05 04:47 UTC, jkmartindale commented
Fully tested my changes with a development deployment of Jekyll, clicking on every link and checking the console to see if any 404 errors popped up.

2021-02-05 09:16 UTC, Korusuke requested changes

2021-02-05 09:16 UTC, Korusuke commented on _config.yml
> +github_username:  mlh-fellowship
nitpick: extra space

2021-02-05 09:16 UTC, Korusuke commented on _includes/header.html
> +    <meta name='twitter:creator' content='@{{ site.twitter_username }}' />
I am not sure about this, but should we add these meta tags conditionally? like only if the username/social image is defined? or even without that this will partially work?

2021-02-05 09:16 UTC, Korusuke commented on _includes/projects.html
> -
any reason for getting rid of this, in this PR?

2021-02-05 17:35 UTC, jkmartindale commented on _includes/projects.html
> -
Woops, that was an experiment that I forgot to revert. I was wondering why changes in `projects.html` weren't affecting output and it turns out `template.html` replaced `projects.html`, `education.html`, and `experience.html` without removing the files.

I'll add the file back, since removing the obsolete files should be a different PR.

2021-02-06 09:28 UTC, Korusuke approved these changes

2021-02-06 09:29 UTC, merged